export const entityContracts = {
  Team: ["id", "name", "code", "flag", "group"],
  Match: [
    "id",
    "stage",
    "homeTeam",
    "awayTeam",
    "homeScore",
    "awayScore",
    "winnerTeamId",
    "decidedBy",
    "penalties",
    "status",
  ],
  Group: ["name", "teamIds", "matches", "standings"],
  StandingRow: [
    "teamId",
    "played",
    "wins",
    "draws",
    "losses",
    "goalsFor",
    "goalsAgainst",
    "goalDifference",
    "points",
    "tieBreakSeed",
  ],
  Round: ["name", "matches", "completed"],
  Tournament: ["teams", "groups", "knockoutRounds", "champion", "status"],
};
